// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback:                       1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    world_forge
    (
        init => init
        upgrade => upgrade
        createNft => create_nft
        issueToken => issue_token
        setLocalRoles => set_local_roles
        buyNft => buy_nft
        commonItems => common_items
        uncommonItems => uncommon_items
        rareItems => rare_items
        epicItems => epic_items
        legendaryItems => legendary_items
        clearAllStorage => clean_all_sotrage
        fillAll => fill_all
        getNftAttributes => get_nft_attributes
    )
}

multiversx_sc_wasm_adapter::async_callback! { world_forge }
